## ATeam docker composer
sonarqube:
    image: sonarqube
    ports:
        - "50001:9000"
jenkins:
    image: tophackathon/ci-java8
    volumes:
        - /c/Users/Lars/dockervolumes/ateam/jenkins:/var/jenkins_home
    ports:
        - "50000:8080"
    links:
        - sonarqube:sonarqube
        
        
    
    
